apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pgop
  namespace: kube-system
spec:
  chart: pgop
  repo: https://ruckc.github.io/pgop
  targetNamespace: pgop-system
  createNamespace: true
