---
apiVersion: pgop.ruck.io/v1alpha1
kind: Cluster
metadata:
  name: enzarb-db
  namespace: enzarb-system
spec: {}
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Role
metadata:
  name: enzarb-app
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Database
metadata:
  name: enzarb
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
  owner: enzarb-app
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Role
metadata:
  name: gitea
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Database
metadata:
  name: gitea
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
  owner: gitea
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Role
metadata:
  name: dex
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
---
apiVersion: pgop.ruck.io/v1alpha1
kind: Database
metadata:
  name: dex
  namespace: enzarb-system
spec:
  clusterRef:
    name: enzarb-db
  owner: dex
