replicaCount: 2

image:
  repository: ghcr.io/enzarb/app
  pullPolicy: IfNotPresent
  tag: ""  # defaults to Chart.appVersion

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

env:
  ORIGIN: https://enzarb.dev
  DATABASE_URL: ""  # loaded from secret

dbSecret:
  name: enzarb-db-app
  key: uri

oidc:
  issuerURL: https://dex.enzarb.dev
  clientID: enzarb-app
  secret:
    name: enzarb-oidc
    clientSecretKey: clientSecret

jwt:
  secret:
    name: enzarb-jwt
    privateKeyKey: privateKey
    publicKeyKey: publicKey

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
