apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: enzarb-app
  namespace: kube-system
spec:
  chart: oci://ghcr.io/enzarb/charts/enzarb-app
  version: 0.1.19
  targetNamespace: enzarb-system
  createNamespace: true
  valuesContent: |-
    image:
      repository: ghcr.io/enzarb/app
    config:
      domain: enzarb.dev
      dexIssuer: https://auth.enzarb.dev
      giteaUrl: https://gitea.enzarb.dev
      registryUrl: https://registry.enzarb.dev
    database:
      host: enzarb-db.enzarb-system
      port: 5432
      name: enzarb
      user: enzarb_app
      passwordSecretRef:
        name: enzarb-db-app-credentials
        key: password
