apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: enzarb-operator
  namespace: kube-system
spec:
  chart: oci://ghcr.io/enzarb/charts/enzarb-operator
  version: 0.1.19
  targetNamespace: enzarb-system
  createNamespace: true
  valuesContent: |-
    leaderElection: true
